name: brew bump
on:
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom (space/newline seperated) list of formulae to livecheck and bump if outdated
        required: false
      casks:
        description: Custom (space/newline seperated) list of casks to livecheck and bump if outdated
        required: false
  schedule:
    - cron: '5 4 5 * *'
    - cron: '5 4 26 * *'

env:
  FORMULAE: >
    pijul
    sshpass

  CASKS: >
    airmessage
    kdeconnect@nightly
    shrugs
    webcord

jobs:
  bump-formula:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        id: set-up-homebrew
      - name: Configure git
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}
      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-
      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems
      - name: Tap hybras/tap
        run: brew tap hybras/tap
      - name: Bump Formula
        uses: Homebrew/actions/bump-packages@master
        with:
          token: ${{ secrets.PAT_GITHUB }}
          formulae: ${{ github.event.inputs.formulae || env.FORMULAE }}
          casks: ${{ github.event.inputs.casks || env.CASKS }}
